logging:
  level:
    org.springframework.security: TRACE

spring:
  application:
    name: pms
  banner:
    location: classpath:banner.txt
  jpa:
    generate-ddl: true # DEVELOPMENT ONLY
    hibernate:
      ddl-auto: create # DEVELOPMENT ONLY
  quartz:
    jdbc:
      initialize-schema: always # DEVELOPMENT ONLY
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true